# @package _global_
args:
  cuda: true
  real: true
  logs: true
  verbose: false
  profile: false
  device: cpu
  output_dir: ""
  result_subdir: ""
  quality: 0
  max_samples: null
  multi_run: false

