multi_run:
  0:
  16:
  32:
  48:
  64:

PROJECT_ROOT: ${oc.env:PROJECT_ROOT}

load:
  path: ${PROJECT_ROOT}/weights/VTC/dinov3-vitl16-slot-1--VTC-vbr.pth.tar
  strict: false
  rules: # type, pattern, replacement
    - ["startswith", "dino.model", "useless"]

resolution_transform:
  type: ResolutionTransform
  mode: center_pad
  size: 64

model: 
  type: MPC_I3
  
  dino_backbone:
    type: cofai.backbone.Dinov3TimmBackbone
    model_size: large
    img_size: 512
    patch_size: 16
    dynamic_size: true
    slot: 24
    n_last_blocks: 1
    pretrained: false
    ckpt_path: ${PROJECT_ROOT}/weights/dinov3/backbone/dinov3_vitl16_pretrain_lvd1689m.safetensors

  dino_codec:
    type: cofai.latent_codecs.VisualTokenCodec
    h_dim: 1024
    y_dim: 120
    z_dim: 48
    groups: 24
    prefix_tokens: 5

allow_heads:
  - ade20k_seg_large_last1
  - nyuv2_dep_large_last1